# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - id: writer
    dir: writer
    binary: main
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
  - id: reader
    dir: reader
    binary: main
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
dockers:
  - builds:
      - reader
    binaries:
      - main
    dockerfile: Dockerfile
    image_templates:
      - "quay.io/mulbc/lockertester:reader"
      - "quay.io/mulbc/lockertester:reader-{{ .Tag }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  - builds:
      - writer
    binaries:
      - main
    dockerfile: Dockerfile
    image_templates:
      - "quay.io/mulbc/lockertester:writer"
      - "quay.io/mulbc/lockertester:writer-{{ .Tag }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
archives:
- format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
env_files:
  # Comment to enable target token
  # github_token: ~/.path/to/my/gh_token
  gitlab_token: ~/.path/to/my/gl_token
  gitea_token: ~/.path/to/my/gitea_token
project_name: lockertester