apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lockertester
  labels:
    app: lockertester
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: px-sharedv3-sc